---
- name: Install and Configure web servers
  hosts: all
  remote_user: opc
  tasks:
  - name: Ensure apache is at the latest version
    ansible.builtin.yum:
      name: httpd
      state: latest # noqa package-latest
    become: yes
  - name: Ensure apache is running
    ansible.builtin.service:
      name: httpd
      state: started
    become: yes
  - name: Copying the Directory's contents (sub directories/files)
    copy:
        src: ~/devops-lab02-ansible/html/
        dest: /var/www/html
        owner: apache
        group: apache
        mode: 0644
    become: yes
  - name: Permit traffic in default zone for http service
    ansible.posix.firewalld:
      service: http
      permanent: true
      state: enabled
      immediate: true
    become: yes
